// <auto-generated />
using System;
using CaesarsTest.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaesarsTest.API.Migrations
{
    [DbContext(typeof(GuestContext))]
    [Migration("20240727160154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaesarsTest.API.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c031dcab-f47f-4f27-b430-129ca4fdae3c"),
                            Address1 = "345 Front St",
                            City = "Atlantic City",
                            DateOfBirth = new DateTime(1980, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fjohnson@kmail.com",
                            FirstName = "Frank",
                            LastName = "Johnson",
                            PhoneNumber = "1234567890",
                            PostalCode = "08201",
                            StateCode = "NJ"
                        },
                        new
                        {
                            Id = new Guid("d2adc02f-e50b-48eb-9278-b24e6fdc1518"),
                            Address1 = "123 Main St",
                            Address2 = "Apt 101",
                            City = "Atlantic City",
                            DateOfBirth = new DateTime(1962, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jwilliams@kmail.com",
                            FirstName = "Jim",
                            LastName = "Williams",
                            PhoneNumber = "2345678901",
                            PostalCode = "08201",
                            StateCode = "NJ"
                        },
                        new
                        {
                            Id = new Guid("d9112bdb-cc4b-4c4d-bbfc-3c69334bc133"),
                            Address1 = "789 Bridge St",
                            City = "Las Vegas",
                            DateOfBirth = new DateTime(1990, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mrichards@kmail.com",
                            FirstName = "Mary",
                            LastName = "Richards",
                            PhoneNumber = "3456789012",
                            PostalCode = "88901",
                            StateCode = "NV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
